---
  TRADE_OPTIONS:
    # In your pairing coin
    QUANTITY: 15
    # BTCUSDT will be bought for example
    PAIRING: USDT
    # HOW OFTEN SHOULD THE BOT DCA, IN DAYS
    DCA_EVERY: 7
    TEST: True
  SEND_NOTIFICATIONS: True
  EMAIL_ADDRESS: bedisarabpreet@gmail.com
  EMAIL_PASSWORD: your gmail password
